apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Grafana.v1beta1.grafana.integreatly.org,GrafanaAlertRuleGroup.v1beta1.grafana.integreatly.org,GrafanaContactPoint.v1beta1.grafana.integreatly.org,GrafanaDashboard.v1beta1.grafana.integreatly.org,GrafanaDatasource.v1beta1.grafana.integreatly.org,GrafanaFolder.v1beta1.grafana.integreatly.org,GrafanaLibraryPanel.v1beta1.grafana.integreatly.org,GrafanaMuteTiming.v1beta1.grafana.integreatly.org,GrafanaNotificationPolicy.v1beta1.grafana.integreatly.org,GrafanaNotificationPolicyRoute.v1beta1.grafana.integreatly.org,GrafanaNotificationTemplate.v1beta1.grafana.integreatly.org
  generateName: grafana-
  namespace: grafana
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/grafana-operator.grafana: ""
  name: grafana-operator
  namespace: grafana
spec:
  channel: v5
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  #startingCSV: grafana-operator.v5.17.1
