apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-rest-python
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/voraviz/simple-rest-python'
    app.openshift.io/connects-to: >-
      [{"apiVersion":"apps/v1","kind":"Deployment","name":"simple-go"}]
  labels:
    app.kubernetes.io/component: simple-rest-python
    app.kubernetes.io/instance: simple-rest-python
    app.kubernetes.io/name: simple-rest-python
    app.kubernetes.io/part-of: App-X
    app.openshift.io/runtime: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-rest-python
      version: v1
  template:
    metadata:
      labels:
        app: simple-rest-python
        version: v1
      # annotations:
      #   instrumentation.opentelemetry.io/inject-nodejs: "true"
    spec:
      containers:
      - name: simple-rest-python
        image: quay.io/voravitl/simple-rest-python:latest
        imagePullPolicy: Always
        env:
          - name: BACKEND
            value: http://simple-go:8080
          # - name: OTEL_EXPORTER_OTLP_ENDPOINT
          #   value: http://otel-collector-headless:4318  
          # - name: OTEL_SERVICE_NAME
          #   value: simple-rest-python
          # - name: OTEL_PROPAGATORS
          #   value: tracecontext,b3
        resources:
          requests:
            cpu: "0.1"
            memory: 60Mi
          limits:
            cpu: "0.2"
            memory: 100Mi
        ports:
        - containerPort: 5000
        securityContext:
          seccompProfile: #"RuntimeDefault" or "Localhost"
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: simple-rest-python
  labels:
    app: simple-rest-python
spec:
  ports:
  - port: 5000
    name: http
    targetPort: 5000
  selector:
    app: simple-rest-python
