apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-rest-dotnet
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: 'https://github.com/voraviz/simple-rest-dotnet'
    app.openshift.io/connects-to: >-
      [{"apiVersion":"apps/v1","kind":"Deployment","name":"backend"}]
  labels:
    app.kubernetes.io/component: simple-rest-dotnet
    app.kubernetes.io/instance: simple-rest-dotnet
    app.kubernetes.io/name: simple-rest-dotnet
    app.kubernetes.io/part-of: App-X
    app.openshift.io/runtime: dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-rest-dotnet
      version: v1
  template:
    metadata:
      labels:
        app: simple-rest-dotnet
        version: v1
      # annotations:
      #   instrumentation.opentelemetry.io/inject-nodejs: "true"
    spec:
      containers:
      - name: simple-rest-dotnet
        image: quay.io/voravitl/simple-rest-dotnet:latest
        imagePullPolicy: Always
        env:
          - name: BACKEND
            value: http://backend:8080
          # - name: OTEL_EXPORTER_OTLP_ENDPOINT
          #   value: http://otel-collector-headless:4318
          # - name: OTEL_SERVICE_NAME
          #   value: simple-rest-dotnet          # - name: OTEL_EXPORTER_OTLP_ENDPOINT
          # - name: OTEL_PROPAGATORS
          #   value: tracecontext,b3
        resources:
          requests:
            cpu: "0.1"
            memory: 60Mi
          limits:
            cpu: "0.2"
            memory: 300Mi
        ports:
        - containerPort: 5000
        securityContext:
          seccompProfile: #"RuntimeDefault" or "Localhost"
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: simple-rest-dotnet
  labels:
    app: simple-rest-dotnet
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: simple-rest-dotnet
