# #namePrefix: prod-
# commonLabels:
#   environment: dev
# commonAnnotations:
#   description: This is Dev environment
# bases:
# - ../../base
# patchesStrategicMerge:
# - todo.yaml
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
# CommonLabels will be added to all resources and selectors
# commonLabels:
#   app: todo
resources:
- ../../base
images:
  - name: quay.io/voravitl/todo 
    newName: quay.io/voravitl/todo 
    newTag: latest 
patches:
- patch: |-

    - op: add
      path: /spec/template/metadata/annotations
      value: 
        instrumentation.opentelemetry.io/inject-java: "true"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-headless:4318"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: OTEL_TRACES_SAMPLER_ARG
        value: "drop=/;drop=/q/health/live;drop=/q/health/ready;fallback=always_on"
    - op: replace
      path: /spec/template/spec/containers/0/readinessProbe/failureThreshold
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/readinessProbe/successThreshold
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/readinessProbe/periodSeconds
      value: 300
    - op: replace
      path: /spec/template/spec/containers/0/livenessProbe/failureThreshold
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/livenessProbe/successThreshold
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/livenessProbe/periodSeconds
      value: 300
  target:
    kind: Deployment
    name: todo
    version: v1
